import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useIsAuthenticated, useMsal } from "@azure/msal-react";
// Note: nav/sign-out are handled by the parent AuthenticatedApp shell in App.tsx
import { useApiClient } from "../hooks/useApiClient";
import { appConfig } from "../config";
import type {
  AiPlaylistEnvelope,
  CachedVideo,
  DeviceCacheCommand,
  ManualPlaylistResponse,
  MediaItem,
  MediaType,
  ResidentCacheResponse,
  ResidentList,
} from "../types";

type UploadRequest = {
  fileName: string;
  type: MediaType | number;
  resident: string;
  contentType?: string | null;
  durationSeconds?: number | null;
};

type UploadResponse = {
  uploadUrl: string;
  blobPath: string;
  expiresAtUtc: string;
};

type MediaRegisterRequest = {
  blobPath: string;
  type: MediaType | number;
  resident: string;
  name?: string | null;
  contentType?: string | null;
  durationSeconds?: number | null;
};

function formatDate(dateString?: string) {
  if (!dateString) return "-";
  return new Intl.DateTimeFormat("en-GB", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(dateString));
}

function formatBytes(bytes?: number | null): string {
  if (bytes == null || bytes <= 0) return "—";
  const mb = bytes / 1024 / 1024;
  if (mb < 1) return `${(bytes / 1024).toFixed(0)} KB`;
  if (mb < 1024) return `${mb.toFixed(1)} MB`;
  return `${(mb / 1024).toFixed(2)} GB`;
}

function formatDuration(seconds?: number | null, fallbackBytes?: number | null): string {
  let s: number | null = null;
  if (seconds != null && seconds > 0) {
    s = Math.floor(seconds);
  } else if (fallbackBytes != null && fallbackBytes > 0) {
    // Same ~2 Mbps assumption the Pi's remote menu uses.
    s = Math.max(1, Math.floor(fallbackBytes / 250_000));
  }
  if (s == null) return "?:??";
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}`;
  return `${m}:${String(sec).padStart(2, "0")}`;
}

function formatRelative(iso?: string | null): string {
  if (!iso) return "—";
  const ms = Date.now() - new Date(iso).getTime();
  if (Number.isNaN(ms)) return "—";
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 48) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}

export default function Dashboard({ isAdmin = false }: { isAdmin?: boolean }) {
  const isAuthed = useIsAuthenticated();
  const { accounts } = useMsal();
  const { call } = useApiClient();

  const [media, setMedia] = useState<MediaItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);

  const [selectedMediaType, setSelectedMediaType] = useState<MediaType>("Photo");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [mediaName, setMediaName] = useState("");
  const [duration, setDuration] = useState<number | undefined>(undefined);

  const [residentList, setResidentList] = useState<string[]>([]);
  const [residentQuery, setResidentQuery] = useState("");
  const [manualText, setManualText] = useState("");
  const [manualMeta, setManualMeta] = useState<{ updatedAt?: string | null; updatedBy?: string | null; lastPolledAt?: string | null }>({});
  const [loadingResident, setLoadingResident] = useState(false);
  const [savingManual, setSavingManual] = useState(false);
  const [generatingAi, setGeneratingAi] = useState(false);
  const [fetchingPhotos, setFetchingPhotos] = useState(false);

  const [seasonalTheme, setSeasonalTheme] = useState("");
  const [radioFavorites, setRadioFavorites] = useState<string[]>([]);
  const [urlInput, setUrlInput] = useState("");
  const [playlistUrls, setPlaylistUrls] = useState<string[]>([]);
  const [saveMessage, setSaveMessage] = useState<string | null>(null);

  // Cached videos on Pi (mirror surfaced by the Pi's snapshot push)
  const [cacheVideos, setCacheVideos] = useState<CachedVideo[]>([]);
  const [cacheDevices, setCacheDevices] = useState<string[]>([]);
  const [cacheLastSeen, setCacheLastSeen] = useState<string | null>(null);
  const [cacheCommands, setCacheCommands] = useState<DeviceCacheCommand[]>([]);
  const [cacheLoading, setCacheLoading] = useState(false);
  const [cacheError, setCacheError] = useState<string | null>(null);
  const [pendingVideoActions, setPendingVideoActions] = useState<Record<string, "delete" | "play">>({});
  const [forceTermInput, setForceTermInput] = useState("");
  const [forceTermCount, setForceTermCount] = useState<number>(3);
  const [forceTermBusy, setForceTermBusy] = useState(false);

  // AI playlist (generated by Pi on button press)
  const [aiPlaylist, setAiPlaylist] = useState<AiPlaylistEnvelope | null>(null);

  // Activity photo viewer state
  const [photoSasUrls, setPhotoSasUrls] = useState<Record<string, string>>({});
  const [photoRotations, setPhotoRotations] = useState<Record<string, number>>({});
  const [photoRenameValues, setPhotoRenameValues] = useState<Record<string, string>>({});
  const [savingPhotoIds, setSavingPhotoIds] = useState<Set<string>>(new Set());
  const loadingPhotoSasRef = useRef<Set<string>>(new Set());

  const accountName = useMemo(() => accounts[0]?.name ?? "Signed-in user", [accounts]);

  const loadData = useCallback(async () => {
    if (!isAuthed) return;
    setLoading(true);
    setError(null);
    try {
      const mediaData = await call<MediaItem[]>({ url: "/api/admin/media", method: "GET" });
      setMedia(mediaData);
    } catch (err) {
      console.error(err);
      setError("Unable to load data. Please check your permissions or API settings.");
    } finally {
      setLoading(false);
    }
  }, [call, isAuthed]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  useEffect(() => {
    const fetchResidents = async () => {
      try {
        const residents = await call<ResidentList>({ url: "/api/admin/residents", method: "GET" });
        setResidentList(residents || []);
      } catch (err) {
        console.error("Failed to load resident list", err);
      }
    };
    fetchResidents();
  }, [call]);

  const residentMedia = useMemo(
    () => residentQuery ? media.filter((m) => m.resident === residentQuery) : [],
    [media, residentQuery]
  );

  const activityPhotos = useMemo(
    () => residentMedia.filter((m) => m.blobPath.includes("/mobizio/")),
    [residentMedia]
  );

  const loadPhotoSas = useCallback(
    async (id: string) => {
      if (loadingPhotoSasRef.current.has(id)) return;
      loadingPhotoSasRef.current.add(id);
      try {
        const sas = await call<{ url: string }>({ url: `/api/admin/media/${id}/sas`, method: "GET" });
        setPhotoSasUrls((prev) => (prev[id] ? prev : { ...prev, [id]: sas.url }));
      } catch {
        loadingPhotoSasRef.current.delete(id);
      }
    },
    [call]
  );

  useEffect(() => {
    activityPhotos.forEach((p) => loadPhotoSas(p.id));
  }, [activityPhotos, loadPhotoSas]);

  const loadResidentManual = useCallback(async () => {
    if (!residentQuery.trim()) {
      setError("Enter a resident name to load playlist.");
      return;
    }
    setLoadingResident(true);
    setError(null);
    try {
      const data = await call<ManualPlaylistResponse>({
        url: `/api/admin/residents/${encodeURIComponent(residentQuery.trim())}/manual-playlist`,
        method: "GET",
      });
      const items = data?.items ?? [] as string[];
      const combined = Array.from(new Set(items));
      setManualText(combined.join("\n"));
      setManualMeta({ updatedAt: data?.updatedAtUtc, updatedBy: data?.updatedBy, lastPolledAt: data?.lastPolledAt });
    } catch (err) {
      console.error(err);
      setManualText("");
      setManualMeta({});
      setError("Could not load playlist for that resident.");
    } finally {
      setLoadingResident(false);
    }
  }, [call, residentQuery]);

  const loadResidentCache = useCallback(async (silent = false) => {
    const r = residentQuery.trim();
    if (!r) return;
    if (!silent) setCacheLoading(true);
    setCacheError(null);
    try {
      const data = await call<ResidentCacheResponse>({
        url: `/api/admin/residents/${encodeURIComponent(r)}/cache`,
        method: "GET",
      });
      setCacheVideos(data?.videos ?? []);
      setCacheDevices(data?.devices ?? []);
      setCacheLastSeen(data?.lastSeenAt ?? null);
    } catch (err) {
      console.error(err);
      if (!silent) setCacheError("Could not load cached videos for that resident.");
    } finally {
      if (!silent) setCacheLoading(false);
    }
  }, [call, residentQuery]);

  const loadCacheCommands = useCallback(async () => {
    const r = residentQuery.trim();
    if (!r) return;
    try {
      const data = await call<DeviceCacheCommand[]>({
        url: `/api/admin/residents/${encodeURIComponent(r)}/cache/commands`,
        method: "GET",
      });
      setCacheCommands(data ?? []);
    } catch (err) {
      console.error(err);
    }
  }, [call, residentQuery]);

  const loadAiPlaylist = useCallback(async () => {
    const r = residentQuery.trim();
    if (!r) return;
    try {
      const data = await call<AiPlaylistEnvelope>({
        url: `/api/admin/residents/${encodeURIComponent(r)}/ai-playlist`,
        method: "GET",
      });
      setAiPlaylist(data ?? null);
    } catch {
      setAiPlaylist(null);
    }
  }, [call, residentQuery]);

  const enqueueDeleteCached = useCallback(async (video: CachedVideo) => {
    const r = residentQuery.trim();
    if (!r) return;
    if (!window.confirm(`Delete '${video.title}' from ${video.deviceId}?\nThe Pi removes the file on its next sync (~30 s).`)) return;
    setPendingVideoActions((prev) => ({ ...prev, [video.id]: "delete" }));
    try {
      await call({
        url: `/api/admin/residents/${encodeURIComponent(r)}/cache/${video.id}`,
        method: "DELETE",
      });
      await loadCacheCommands();
    } catch (err) {
      console.error(err);
      setCacheError("Failed to enqueue delete command.");
      setPendingVideoActions((prev) => {
        const next = { ...prev };
        delete next[video.id];
        return next;
      });
    }
  }, [call, residentQuery, loadCacheCommands]);

  const enqueuePlayCached = useCallback(async (video: CachedVideo) => {
    const r = residentQuery.trim();
    if (!r) return;
    setPendingVideoActions((prev) => ({ ...prev, [video.id]: "play" }));
    try {
      await call({
        url: `/api/admin/residents/${encodeURIComponent(r)}/cache/${video.id}/play`,
        method: "POST",
      });
      await loadCacheCommands();
    } catch (err) {
      console.error(err);
      setCacheError("Failed to enqueue play command.");
      setPendingVideoActions((prev) => {
        const next = { ...prev };
        delete next[video.id];
        return next;
      });
    }
  }, [call, residentQuery, loadCacheCommands]);

  const enqueueForceTerm = useCallback(async () => {
    const r = residentQuery.trim();
    const term = forceTermInput.trim();
    if (!r || !term) return;
    setForceTermBusy(true);
    try {
      await call({
        url: `/api/admin/residents/${encodeURIComponent(r)}/cache/force-term`,
        method: "POST",
        data: { term, count: forceTermCount },
      });
      setForceTermInput("");
      await loadCacheCommands();
    } catch (err) {
      console.error(err);
      setCacheError("Failed to enqueue force-term command.");
    } finally {
      setForceTermBusy(false);
    }
  }, [call, residentQuery, forceTermInput, forceTermCount, loadCacheCommands]);

  // Auto-refresh while a resident is selected: poll every 15 s for new
  // snapshot pushes from the Pi and any newly-acked commands.
  useEffect(() => {
    if (!residentQuery.trim()) return;
    loadResidentCache();
    loadCacheCommands();
    loadAiPlaylist();
    const t = window.setInterval(() => {
      loadResidentCache(true);
      loadCacheCommands();
      loadAiPlaylist();
    }, 15000);
    return () => window.clearInterval(t);
  }, [residentQuery, loadResidentCache, loadCacheCommands, loadAiPlaylist]);

  const saveResidentManual = useCallback(
    async (overrideItems?: string[]) => {
      if (!residentQuery.trim()) {
        setError("Resident name is required.");
        return;
      }
      const items =
        overrideItems ??
        manualText
          .split(/\r?\n/)
          .map((l) => l.trim())
          .filter(Boolean);
      setSavingManual(true);
      setError(null);
      try {
        await call({
          url: `/api/admin/residents/${encodeURIComponent(residentQuery.trim())}/manual-playlist`,
          method: "PUT",
          data: { items },
        });
        setManualMeta((prev) => ({ ...prev, updatedAt: new Date().toISOString(), updatedBy: accountName, lastPolledAt: prev.lastPolledAt }));
        setSaveMessage("Manual playlist saved.");
      } catch (err) {
        console.error(err);
        setError("Failed to save manual playlist.");
      } finally {
        setSavingManual(false);
      }
    },
    [accountName, call, manualText, residentQuery]
  );

  const saveRadioToPlaylist = useCallback(async () => {
    if (!residentQuery.trim()) {
      setError("Select a resident first.");
      return;
    }
    if (!radioFavorites.length) {
      setError("Select at least one radio station.");
      return;
    }
    const radioLines = radioFavorites.map((u) => `radio:${u}`);
    const existing = manualText.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
    const existingSet = new Set(existing);
    const toAdd = radioLines.filter((l) => !existingSet.has(l));
    const updated = [...existing, ...toAdd];
    setManualText(updated.join("\n"));
    await saveResidentManual(updated);
    setSaveMessage(toAdd.length ? `${toAdd.length} radio station(s) added to playlist.` : "Radio stations already in playlist.");
  }, [radioFavorites, manualText, residentQuery, saveResidentManual]);

  const deleteResident = useCallback(async () => {
    const r = residentQuery.trim();
    if (!r) return;
    const first = window.confirm(
      `Delete resident "${r}" from the portal?\n\n` +
      `This removes their playlist snapshot, cache mirror rows, access grants, ` +
      `and detaches any Pi assigned to them. It cannot be undone.`
    );
    if (!first) return;
    const second = window.prompt(`Type the resident name to confirm: ${r}`);
    if (second !== r) {
      if (second !== null) setError("Name didn't match — delete cancelled.");
      return;
    }
    setError(null);
    setSaveMessage(null);
    try {
      const result = await call<{
        resident: string;
        devicesDetached: number;
        cachedVideosDeleted: number;
        accessGrantsDeleted: number;
      }>({
        url: `/api/admin/residents/${encodeURIComponent(r)}`,
        method: "DELETE",
      });
      setSaveMessage(
        `Deleted "${result.resident}" — ${result.devicesDetached} device(s) detached, ` +
        `${result.cachedVideosDeleted} cached video row(s), ` +
        `${result.accessGrantsDeleted} access grant(s).`
      );
      setResidentQuery("");
      setManualText("");
      setManualMeta({});
      setCacheVideos([]);
      setCacheDevices([]);
      setCacheLastSeen(null);
      setAiPlaylist(null);
      try {
        const residents = await call<ResidentList>({ url: "/api/admin/residents", method: "GET" });
        setResidentList(residents || []);
      } catch (refreshErr) {
        console.error("Failed to refresh resident list", refreshErr);
      }
    } catch (err) {
      console.error(err);
      setError("Failed to delete resident.");
    }
  }, [call, residentQuery]);

  const applySeasonalToPlaylist = useCallback(async () => {
    if (!residentQuery.trim()) {
      setError("Select a resident first.");
      return;
    }
    const existing = manualText.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
    const filtered = existing.filter((l) => !l.startsWith("season:"));
    const updated = seasonalTheme ? [...filtered, `season:${seasonalTheme}`] : filtered;
    setManualText(updated.join("\n"));
    await saveResidentManual(updated);
    setSaveMessage(seasonalTheme ? `Seasonal focus "${seasonalTheme}" applied to playlist.` : "Seasonal focus cleared from playlist.");
  }, [seasonalTheme, manualText, residentQuery, saveResidentManual]);

  const onGenerateAiSuggestions = useCallback(async () => {
    if (!residentQuery.trim()) {
      setError("Select a resident before generating suggestions.");
      return;
    }
    setGeneratingAi(true);
    setError(null);
    try {
      const result = await call<{ items: string[] }>({
        url: `/api/admin/residents/${encodeURIComponent(residentQuery.trim())}/ai-suggestions`,
        method: "POST",
      });
      const newItems = result?.items ?? [];
      if (!newItems.length) {
        setError("No suggestions returned. The resident may not have a care plan in Access Care Planning.");
        return;
      }
      const existing = manualText.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
      const existingSet = new Set(existing.map((s) => s.toLowerCase()));
      const toAdd = newItems.filter((s) => !existingSet.has(s.toLowerCase()));
      const updated = [...existing, ...toAdd];
      setManualText(updated.join("\n"));
      await saveResidentManual(updated);
      setSaveMessage(`Added ${toAdd.length} AI suggestions to the playlist.`);
    } catch (err: any) {
      console.error(err);
      const msg = err?.response?.data || err?.message || "Unknown error";
      setError(`AI suggestions failed: ${msg}`);
    } finally {
      setGeneratingAi(false);
    }
  }, [call, manualText, residentQuery, saveResidentManual]);

  const onFetchActivityPhotos = useCallback(async () => {
    if (!residentQuery.trim()) {
      setError("Select a resident before fetching activity photos.");
      return;
    }
    setFetchingPhotos(true);
    setError(null);
    try {
      const result = await call<{ count: number; mediaIds: string[] }>({
        url: `/api/admin/residents/${encodeURIComponent(residentQuery.trim())}/fetch-activity-photos`,
        method: "POST",
        timeout: 180000,
      });
      if (!result?.count) {
        setSaveMessage("No new activity photos found in Access Care Planning for this resident.");
        return;
      }
      const newTokens = (result.mediaIds ?? []).map((id) => `media:${id}`);
      const existing = manualText.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
      const existingSet = new Set(existing);
      const toAdd = newTokens.filter((t) => !existingSet.has(t));
      const updated = [...existing, ...toAdd];
      setManualText(updated.join("\n"));
      await saveResidentManual(updated);
      setSaveMessage(`${result.count} activity photo(s) imported from Access Care Planning and added to playlist.`);
      await loadData();
    } catch (err: any) {
      console.error(err);
      setError(`Failed to fetch activity photos: ${err?.message ?? "Unknown error"}`);
    } finally {
      setFetchingPhotos(false);
    }
  }, [call, loadData, manualText, residentQuery, saveResidentManual]);

  const onUploadMedia = useCallback(
    async (evt: React.FormEvent) => {
      evt.preventDefault();
      if (!residentQuery.trim()) {
        setError("Select a resident before uploading media.");
        return;
      }
      if (!selectedFile) {
        setError("Select a file to upload.");
        return;
      }
      setUploading(true);
      setError(null);
      try {
        const apiMediaType = selectedMediaType === "Photo" ? 0 : 1;
        const uploadBody: UploadRequest = {
          fileName: selectedFile.name,
          type: apiMediaType as unknown as MediaType,
          resident: residentQuery.trim(),
          contentType: selectedFile.type || null,
          durationSeconds: duration || null,
        };

        const upload = await call<UploadResponse>({
          url: "/api/admin/media/upload-url",
          method: "POST",
          data: uploadBody,
        });

        await fetch(upload.uploadUrl, {
          method: "PUT",
          headers: {
            "x-ms-blob-type": "BlockBlob",
            "Content-Type": selectedFile.type || "application/octet-stream",
          },
          body: selectedFile,
        });

        const registerBody: MediaRegisterRequest = {
          blobPath: upload.blobPath,
          type: apiMediaType as unknown as MediaType,
          resident: residentQuery.trim(),
          name: mediaName || selectedFile.name,
          contentType: selectedFile.type || null,
          durationSeconds: duration || null,
        };

        const registerResponse = await call<{ mediaId: string }>({
          url: "/api/admin/media",
          method: "POST",
          data: registerBody,
        });

        const mediaToken =
          registerResponse?.mediaId ? `media:${registerResponse.mediaId}` : mediaName || selectedFile.name;
        const existing = manualText.split(/\r?\n/).filter(Boolean);
        const updated = Array.from(new Set([...existing, mediaToken]));
        setManualText(updated.join("\n"));
        await saveResidentManual(updated);

        setSelectedFile(null);
        setMediaName("");
        setDuration(undefined);
        await loadData();
      } catch (err: any) {
        console.error(err);
        const serverMessage =
          err?.response?.data && typeof err.response.data === "string"
            ? err.response.data
            : err?.response?.data?.message ||
              err?.response?.data?.error ||
              err?.message;
        setError(
          serverMessage
            ? `Upload failed: ${serverMessage}`
            : "Upload failed. Check storage settings and try again."
        );
      } finally {
        setUploading(false);
      }
    },
    [call, duration, loadData, manualText, mediaName, saveResidentManual, selectedFile, selectedMediaType]
  );

  const savePhotoRotation = useCallback(
    async (photo: MediaItem) => {
      const angle = photoRotations[photo.id] ?? 0;
      if (angle === 0) return;
      const sasUrl = photoSasUrls[photo.id];
      if (!sasUrl) return;

      setSavingPhotoIds((prev) => new Set(prev).add(photo.id));
      try {
        const img = new Image();
        img.crossOrigin = "anonymous";
        await new Promise<void>((resolve, reject) => {
          img.onload = () => resolve();
          img.onerror = () => reject(new Error("Image load failed"));
          img.src = sasUrl;
        });

        const rad = (angle * Math.PI) / 180;
        const sin = Math.abs(Math.sin(rad));
        const cos = Math.abs(Math.cos(rad));
        const w = Math.round(img.width * cos + img.height * sin);
        const h = Math.round(img.width * sin + img.height * cos);

        const canvas = document.createElement("canvas");
        canvas.width = w;
        canvas.height = h;
        const ctx = canvas.getContext("2d")!;
        ctx.translate(w / 2, h / 2);
        ctx.rotate(rad);
        ctx.drawImage(img, -img.width / 2, -img.height / 2);

        const contentType = photo.contentType || "image/jpeg";
        const blob = await new Promise<Blob>((resolve, reject) =>
          canvas.toBlob((b) => (b ? resolve(b) : reject(new Error("Canvas toBlob failed"))), contentType)
        );

        const fileName = photo.blobPath.split("/").pop() ?? "rotated.jpg";
        const upload = await call<UploadResponse>({
          url: "/api/admin/media/upload-url",
          method: "POST",
          data: { fileName, type: 0, resident: photo.resident || residentQuery.trim() },
        });

        await fetch(upload.uploadUrl, {
          method: "PUT",
          headers: { "x-ms-blob-type": "BlockBlob", "Content-Type": contentType },
          body: blob,
        });

        await call({ url: `/api/admin/media/${photo.id}`, method: "PATCH", data: { blobPath: upload.blobPath } });

        const newSas = await call<{ url: string }>({ url: `/api/admin/media/${photo.id}/sas`, method: "GET" });
        setPhotoSasUrls((prev) => ({ ...prev, [photo.id]: newSas.url }));
        setPhotoRotations((prev) => { const n = { ...prev }; delete n[photo.id]; return n; });
        setSaveMessage("Photo rotation saved.");
      } catch (err: any) {
        setError(`Failed to save rotation: ${err?.message ?? "Unknown error"}`);
      } finally {
        setSavingPhotoIds((prev) => { const n = new Set(prev); n.delete(photo.id); return n; });
      }
    },
    [call, photoRotations, photoSasUrls, residentQuery]
  );

  const renamePhoto = useCallback(
    async (id: string) => {
      const newName = photoRenameValues[id]?.trim();
      if (!newName) return;
      setSavingPhotoIds((prev) => new Set(prev).add(id));
      try {
        await call({ url: `/api/admin/media/${id}`, method: "PATCH", data: { name: newName } });
        await loadData();
        setSaveMessage("Photo renamed.");
      } catch (err: any) {
        setError(`Failed to rename: ${err?.message ?? "Unknown error"}`);
      } finally {
        setSavingPhotoIds((prev) => { const n = new Set(prev); n.delete(id); return n; });
      }
    },
    [call, loadData, photoRenameValues]
  );


  const radioPresets = [
    { name: "BBC Radio 1", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_radio_one&bitrate=128000" },
    { name: "BBC Radio 2", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_radio_two&bitrate=128000" },
    { name: "BBC Radio 3", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_radio_three&bitrate=128000" },
    { name: "BBC Radio 4", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_radio_fourfm&bitrate=128000" },
    { name: "BBC Radio 5 Live", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_radio_five_live&bitrate=128000" },
    { name: "BBC Radio 6 Music", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_6music&bitrate=128000" },
    { name: "BBC Radio 4 Extra", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_radio_four_extra&bitrate=128000" },
    { name: "BBC Radio Bristol", url: "https://lsn.lv/bbcradio.m3u8?station=bbc_radio_bristol&bitrate=128000" },
  ];

  const seasonalOptions = ["", "Christmas", "Easter", "Diwali", "Eid", "Hanukkah", "Remembrance", "Summer", "Winter"];

  return (
    <>
      <section className="hero">
        <div className="hero-left">
          <div className="hero-eyebrow">Bristol Care Homes</div>
          <h1 className="hero-title">Design soothing playlists for your loved ones.</h1>
          <p className="hero-copy">
            Upload photos or videos, arrange them into playlists, and assign them to
            any Media Button Pi in seconds. Secure sign-in via your home tenant keeps
            residents' memories private and staff workflows simple.
          </p>
          <div className="pill brand-pill">Providing top quality, best value, holistic care.</div>
          <div className="nav-actions">
            <div className="badge">
              <span className="status-dot" />
              Home tenant: {appConfig.auth.tenantId || "Configure tenant ID"}
            </div>
          </div>
        </div>

        <div className="hero-right">
          <div className="logo-card glass">
            <img src="/press-play-hero.svg" alt="Press & Play Media Button" className="hero-logo" />
            <p className="hero-mini">
              Signed in as {accountName}. Press &amp; Play keeps playlists familiar, safe, and easy
              for every resident.
            </p>
          </div>
        </div>
      </section>

      <main className="content">
        {error && (
          <div className="card" style={{ borderColor: "rgba(217,72,15,0.3)" }}>
            <strong style={{ color: "var(--warning)" }}>Heads up: </strong>
            <span className="muted">{error}</span>
          </div>
        )}
        {saveMessage && (
          <div className="card glass">
            <strong style={{ color: "var(--brand-strong)" }}>Saved: </strong>
            <span className="muted">{saveMessage}</span>
          </div>
        )}

        <div className="card glass">
          <div className="card-header">
            <p className="card-title">Resident playlist</p>
            <span className="tag">Load current playlist first</span>
          </div>
          <div className="form-row">
            <select className="select" value={residentQuery} onChange={(e) => setResidentQuery(e.target.value)}>
              <option value="">Select resident...</option>
              {residentList.map((r) => (
                <option key={r} value={r}>
                  {r}
                </option>
              ))}
            </select>
            <div className="nav-actions" style={{ gap: 8 }}>
              <button className="btn ghost" type="button" disabled={loadingResident} onClick={loadResidentManual}>
                {loadingResident ? "Loading..." : "Load current playlist"}
              </button>
              {isAdmin && residentQuery.trim() && (
                <button
                  className="btn ghost"
                  type="button"
                  onClick={deleteResident}
                  style={{ color: "var(--warning, #ff6b6b)", borderColor: "var(--warning, #ff6b6b)" }}
                  title="Hard-delete this resident from the portal"
                >
                  Delete resident
                </button>
              )}
            </div>
          </div>
        </div>

        {residentQuery.trim() && (
          <div className="card glass">
            <div className="card-header">
              <p className="card-title">Cached videos on Pi</p>
              <span className="tag">
                {cacheDevices.length === 0
                  ? "No device snapshot yet"
                  : `${cacheVideos.length} video(s) • ${cacheDevices.length} device(s) • last seen ${formatRelative(cacheLastSeen)}`}
              </span>
            </div>

            {cacheError && (
              <div className="muted" style={{ color: "var(--warning)" }}>{cacheError}</div>
            )}

            {cacheLoading && cacheVideos.length === 0 ? (
              <div className="muted">Loading.</div>
            ) : cacheVideos.length === 0 ? (
              <div className="muted">
                Nothing cached for this resident yet. The Pi pushes its inventory every few minutes;
                if you're sure videos are cached on the device, check that the Pi is online and that
                the cache subsystem is running.
              </div>
            ) : (
              <div style={{ overflowX: "auto" }}>
                <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 14 }}>
                  <thead>
                    <tr style={{ textAlign: "left", borderBottom: "1px solid rgba(255,255,255,0.1)" }}>
                      <th style={{ padding: "8px 6px" }}>Title</th>
                      <th style={{ padding: "8px 6px" }}>Term</th>
                      <th style={{ padding: "8px 6px" }}>Duration</th>
                      <th style={{ padding: "8px 6px" }}>Size</th>
                      <th style={{ padding: "8px 6px" }}>Downloaded</th>
                      <th style={{ padding: "8px 6px" }}>Last played</th>
                      <th style={{ padding: "8px 6px" }}>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {cacheVideos.map((v) => {
                      const pending = pendingVideoActions[v.id];
                      return (
                        <tr key={v.id} style={{ borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
                          <td style={{ padding: "6px" }}>
                            <div style={{ fontWeight: 600 }}>{v.title}</div>
                            <div className="muted" style={{ fontSize: 12 }}>
                              {v.source}:{v.sourceId}
                              {v.protected ? " • protected" : ""}
                            </div>
                          </td>
                          <td style={{ padding: "6px" }} className="muted">{v.term ?? "—"}</td>
                          <td style={{ padding: "6px" }}>{formatDuration(v.durationSeconds, v.filesizeBytes)}</td>
                          <td style={{ padding: "6px" }}>{formatBytes(v.filesizeBytes)}</td>
                          <td style={{ padding: "6px" }} title={v.downloadedAt}>{formatRelative(v.downloadedAt)}</td>
                          <td style={{ padding: "6px" }} title={v.lastPlayedAt ?? ""}>{formatRelative(v.lastPlayedAt)} {v.playCount ? `(×${v.playCount})` : ""}</td>
                          <td style={{ padding: "6px", whiteSpace: "nowrap" }}>
                            <button
                              className="btn ghost"
                              type="button"
                              style={{ padding: "4px 10px", marginRight: 6 }}
                              disabled={!!pending}
                              onClick={() => enqueuePlayCached(v)}
                              title="Start a session on the Pi with just this video"
                            >
                              {pending === "play" ? "queued." : "▶ Play"}
                            </button>
                            <button
                              className="btn ghost"
                              type="button"
                              style={{ padding: "4px 10px" }}
                              disabled={!!pending || v.protected}
                              onClick={() => enqueueDeleteCached(v)}
                              title={v.protected ? "Protected uploads cannot be deleted" : "Remove from Pi on next sync"}
                            >
                              {pending === "delete" ? "queued." : "🗑 Delete"}
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}

            <div style={{ marginTop: 16, borderTop: "1px solid rgba(255,255,255,0.08)", paddingTop: 12 }}>
              <div className="card-header" style={{ marginBottom: 6 }}>
                <p className="card-title" style={{ fontSize: 14 }}>Force download for a term</p>
                <span className="tag">Pi fetches more candidates next sync</span>
              </div>
              <div className="form-row" style={{ alignItems: "flex-end" }}>
                <label className="grid" style={{ flex: 3 }}>
                  <span className="muted">Search term (e.g. "Vera Lynn songs")</span>
                  <input
                    className="input"
                    value={forceTermInput}
                    onChange={(e) => setForceTermInput(e.target.value)}
                    placeholder="Vera Lynn songs"
                  />
                </label>
                <label className="grid" style={{ flex: 1 }}>
                  <span className="muted">Count</span>
                  <input
                    className="input"
                    type="number"
                    min={1}
                    max={10}
                    value={forceTermCount}
                    onChange={(e) => setForceTermCount(Math.max(1, Math.min(10, Number(e.target.value) || 3)))}
                  />
                </label>
                <button
                  className="btn primary"
                  type="button"
                  disabled={forceTermBusy || !forceTermInput.trim() || cacheDevices.length === 0}
                  onClick={enqueueForceTerm}
                >
                  {forceTermBusy ? "Queueing." : "Queue downloads"}
                </button>
              </div>
              {cacheDevices.length === 0 && (
                <div className="muted" style={{ fontSize: 12 }}>
                  Needs at least one device assigned to this resident before download commands can be enqueued.
                </div>
              )}
            </div>

            {cacheCommands.length > 0 && (
              <div style={{ marginTop: 12, fontSize: 13 }}>
                <div className="muted" style={{ marginBottom: 4 }}>Pending commands</div>
                <div className="list" style={{ gap: 2 }}>
                  {cacheCommands.map((c) => (
                    <div key={c.id} className="row" style={{ fontSize: 12 }}>
                      <span>{c.commandType} → <span className="muted">{c.deviceId}</span></span>
                      <span className="tag">{c.status} • {formatRelative(c.createdAt)}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        <div className="split">
          <div className="card glass">
            <div className="card-header">
              <p className="card-title">Upload media</p>
              <span className="tag">Direct-to-blob SAS</span>
            </div>
            <form className="grid" onSubmit={onUploadMedia}>
              <div className="form-row">
                <label className="grid">
                  <span className="muted">Choose file</span>
                  <input
                    type="file"
                    className="input"
                    onChange={(e) => setSelectedFile(e.target.files?.[0] ?? null)}
                    accept="image/*,video/*"
                  />
                </label>
                <label className="grid">
                  <span className="muted">Type</span>
                  <select
                    className="select"
                    value={selectedMediaType}
                    onChange={(e) => setSelectedMediaType(e.target.value as MediaType)}
                  >
                    <option value="Photo">Photo</option>
                    <option value="Video">Video</option>
                  </select>
                </label>
              </div>
              <div className="form-row">
                <label className="grid">
                  <span className="muted">Display name (optional)</span>
                  <input
                    className="input"
                    value={mediaName}
                    onChange={(e) => setMediaName(e.target.value)}
                    placeholder="Sunset walk in Clifton"
                  />
                </label>
                <label className="grid">
                  <span className="muted">Duration seconds (optional for videos)</span>
                  <input
                    className="input"
                    type="number"
                    value={duration ?? ""}
                    onChange={(e) =>
                      setDuration(e.target.value ? Number(e.target.value) : undefined)
                    }
                    min={0}
                  />
                </label>
              </div>
              <button className="btn primary" type="submit" disabled={uploading}>
                {uploading ? "Uploading..." : "Upload & register"}
              </button>
            </form>
          </div>

          <div className="card glass">
            <div className="card-header">
              <p className="card-title">Radio favourites</p>
              <span className="tag">BBC stations</span>
            </div>
            <div className="list" style={{ gap: 6 }}>
              {radioPresets.map((r) => {
                const checked = radioFavorites.includes(r.url);
                const disabled = !checked && radioFavorites.length >= 3;
                return (
                  <label className="row" key={r.url}>
                    <div style={{ fontWeight: 700 }}>{r.name}</div>
                    <input
                      type="checkbox"
                      checked={checked}
                      disabled={disabled}
                      onChange={(e) => {
                        setRadioFavorites((prev) =>
                          e.target.checked ? [...prev, r.url] : prev.filter((u) => u !== r.url)
                        );
                      }}
                    />
                  </label>
                );
              })}
            </div>
            <button
              className="btn primary"
              type="button"
              style={{ marginTop: 12 }}
              disabled={!radioFavorites.length || !residentQuery.trim()}
              onClick={saveRadioToPlaylist}
            >
              Save radio to playlist
            </button>
          </div>
        </div>

        <div className="split">
          <div className="card glass">
            <div className="card-header">
              <p className="card-title">Seasonal influence</p>
              <span className="tag">Optional theme</span>
            </div>
            <select className="select" value={seasonalTheme} onChange={(e) => setSeasonalTheme(e.target.value)}>
              {seasonalOptions.map((s) => (
                <option key={s || "none"} value={s}>
                  {s || "No seasonal focus"}
                </option>
              ))}
            </select>
            <button
              className="btn primary"
              type="button"
              style={{ marginTop: 12 }}
              disabled={!residentQuery.trim()}
              onClick={applySeasonalToPlaylist}
            >
              Apply to playlist
            </button>
          </div>

          <div className="card glass">
            <div className="card-header">
              <p className="card-title">Add stream/media URLs</p>
              <span className="tag">Playlists &amp; radio</span>
            </div>
            <div className="grid" style={{ gap: 8 }}>
              <div className="form-row">
                <input
                  className="input"
                  placeholder="https://example.com/stream.mp3"
                  value={urlInput}
                  onChange={(e) => setUrlInput(e.target.value)}
                />
                <button className="btn ghost" type="button" onClick={loadResidentManual} disabled={loadingResident}>
                  Reload playlist
                </button>
                <button className="btn ghost" type="button" onClick={() => setUrlInput("")} disabled={!urlInput.trim()}>
                  Clear
                </button>
              </div>
              <button className="btn primary" type="button" onClick={() => {
                if (!urlInput.trim()) return;
                const existing = manualText.split(/\r?\n/).filter(Boolean);
                const updated = Array.from(new Set([...existing, urlInput.trim()]));
                setManualText(updated.join("\n"));
                setPlaylistUrls((prev) => (prev.includes(urlInput.trim()) ? prev : [...prev, urlInput.trim()]));
                saveResidentManual(updated);
                setUrlInput("");
              }}>
                Add URL to playlist
              </button>
              {!!playlistUrls.length && (
                <div className="list">
                  {playlistUrls.map((u) => (
                    <div className="row" key={u}>
                      <span style={{ wordBreak: "break-all" }}>{u}</span>
                      <button
                        className="btn ghost"
                        type="button"
                        onClick={() => {
                          setPlaylistUrls((prev) => prev.filter((x) => x !== u));
                          const updated = manualText
                            .split(/\r?\n/)
                            .map((l) => l.trim())
                            .filter(Boolean)
                            .filter((line) => line !== u);
                          setManualText(updated.join("\n"));
                          saveResidentManual(updated);
                        }}
                      >
                        Remove
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="card glass">
          <div className="card-header">
            <p className="card-title">Manual playlist</p>
            <span className="muted">
              One entry per line. Device receives blob URLs at poll time.
            </span>
          </div>
          <textarea
            className="textarea"
            style={{ minHeight: 200 }}
            value={manualText}
            onChange={(e) => setManualText(e.target.value)}
            placeholder="Enter titles, URLs or radio: prefixed stations"
          />
          <div className="nav-actions" style={{ justifyContent: "space-between", width: "100%" }}>
            <div className="muted" style={{ display: "flex", alignItems: "center", gap: 10 }}>
              {manualMeta.updatedAt && (
                <span>
                  Last saved {formatDate(manualMeta.updatedAt)} {manualMeta.updatedBy ? `by ${manualMeta.updatedBy}` : ""}
                </span>
              )}
              {manualMeta.updatedAt && (() => {
                const polled = manualMeta.lastPolledAt ? new Date(manualMeta.lastPolledAt) : null;
                const saved = new Date(manualMeta.updatedAt);
                const isLive = polled !== null && polled >= saved;
                return isLive ? (
                  <span className="pill" style={{ background: "rgba(34,197,94,0.15)", color: "#22c55e", fontSize: 12, gap: 4 }}>
                    <span className="status-dot" style={{ background: "#22c55e" }} />
                    Live on device
                  </span>
                ) : (
                  <span className="pill" style={{ background: "rgba(234,179,8,0.15)", color: "#ca8a04", fontSize: 12, gap: 4 }}>
                    <span className="status-dot" style={{ background: "#ca8a04" }} />
                    Pending sync
                  </span>
                );
              })()}
            </div>
            <div className="nav-actions" style={{ gap: 8 }}>
              <button
                className="btn ghost"
                type="button"
                disabled={fetchingPhotos || !residentQuery.trim()}
                onClick={onFetchActivityPhotos}
                title="Import recent activity record photos from Access Care Planning into the playlist"
              >
                {fetchingPhotos ? "Importing..." : "Import activity photos"}
              </button>
              <button
                className="btn ghost"
                type="button"
                disabled={generatingAi || !residentQuery.trim()}
                onClick={onGenerateAiSuggestions}
                title="Fetch care plan from Access Care Planning and generate personalised suggestions"
              >
                {generatingAi ? "Generating..." : "Generate AI suggestions"}
              </button>
              <button className="btn ghost" type="button" disabled={loadingResident} onClick={loadResidentManual}>
                Reload
              </button>
              <button className="btn primary" type="button" disabled={savingManual} onClick={() => saveResidentManual()}>
                {savingManual ? "Saving..." : "Save manual playlist"}
              </button>
            </div>
          </div>
        </div>

        {aiPlaylist && (
          <div className="card glass">
            <div className="card-header">
              <p className="card-title">AI playlist (generated by device)</p>
              <span className="muted">
                {aiPlaylist.payload?.playlist?.length ?? 0} term(s)
                {aiPlaylist.updatedAtUtc ? ` · updated ${formatRelative(aiPlaylist.updatedAtUtc)}` : ""}
              </span>
            </div>
            <ol style={{ margin: 0, padding: "0 0 0 20px", display: "flex", flexDirection: "column", gap: 4 }}>
              {(aiPlaylist.payload?.playlist ?? []).map((term, i) => (
                <li key={i} style={{ fontSize: 13 }}>{term}</li>
              ))}
            </ol>
          </div>
        )}

        {activityPhotos.length > 0 && (
          <div className="card glass">
            <div className="card-header">
              <p className="card-title">Activity photos from Access Care Planning</p>
              <span className="muted">{activityPhotos.length} photo(s){residentQuery ? ` for ${residentQuery}` : ""}</span>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 16 }}>
              {activityPhotos.map((photo) => {
                const sasUrl = photoSasUrls[photo.id];
                const rotation = photoRotations[photo.id] ?? 0;
                const isSaving = savingPhotoIds.has(photo.id);
                const renameVal = photoRenameValues[photo.id] ?? photo.name ?? "";
                return (
                  <div key={photo.id} className="card" style={{ padding: 12, gap: 10 }}>
                    <div
                      style={{
                        height: 180,
                        background: "rgba(0,0,0,0.1)",
                        borderRadius: 8,
                        overflow: "hidden",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                      }}
                    >
                      {sasUrl ? (
                        <img
                          src={sasUrl}
                          alt={photo.name ?? "Activity photo"}
                          style={{
                            maxWidth: "100%",
                            maxHeight: "100%",
                            objectFit: "contain",
                            transform: `rotate(${rotation}deg)`,
                            transition: "transform 0.2s",
                          }}
                        />
                      ) : (
                        <span className="muted" style={{ fontSize: 13 }}>Loading...</span>
                      )}
                    </div>
                    <div className="muted" style={{ fontSize: 12 }}>{formatDate(photo.uploadedAt)}</div>
                    <div className="form-row" style={{ gap: 6 }}>
                      <input
                        className="input"
                        style={{ flex: 1, fontSize: 13 }}
                        value={renameVal}
                        onChange={(e) => setPhotoRenameValues((prev) => ({ ...prev, [photo.id]: e.target.value }))}
                        placeholder="Enter a name for this photo"
                        onKeyDown={(e) => { if (e.key === "Enter") renamePhoto(photo.id); }}
                      />
                      <button
                        className="btn ghost"
                        type="button"
                        disabled={isSaving || !renameVal.trim() || renameVal.trim() === (photo.name ?? "")}
                        onClick={() => renamePhoto(photo.id)}
                        style={{ whiteSpace: "nowrap" }}
                      >
                        Rename
                      </button>
                    </div>
                    <div className="nav-actions" style={{ gap: 6, justifyContent: "space-between" }}>
                      <div className="nav-actions" style={{ gap: 6 }}>
                        <button
                          className="btn ghost"
                          type="button"
                          disabled={!sasUrl}
                          onClick={() => setPhotoRotations((prev) => ({ ...prev, [photo.id]: ((prev[photo.id] ?? 0) + 270) % 360 }))}
                          title="Rotate left"
                        >
                          ↺
                        </button>
                        <button
                          className="btn ghost"
                          type="button"
                          disabled={!sasUrl}
                          onClick={() => setPhotoRotations((prev) => ({ ...prev, [photo.id]: ((prev[photo.id] ?? 0) + 90) % 360 }))}
                          title="Rotate right"
                        >
                          ↻
                        </button>
                        <button
                          className="btn primary"
                          type="button"
                          disabled={isSaving || !sasUrl || rotation === 0}
                          onClick={() => savePhotoRotation(photo)}
                          style={{ fontSize: 12 }}
                        >
                          {isSaving ? "Saving..." : "Save rotation"}
                        </button>
                      </div>
                      <button
                        className="btn ghost"
                        type="button"
                        onClick={async () => {
                          try {
                            await call({ url: `/api/admin/media/${photo.id}`, method: "DELETE" });
                            await loadData();
                          } catch {
                            setError("Could not delete photo.");
                          }
                        }}
                        style={{ fontSize: 12, color: "var(--warning)" }}
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <div className="card glass">
          <div className="card-header">
            <p className="card-title">Media library</p>
            <span className="muted">
              {!residentQuery ? "Select a resident to view their media" : loading ? "Loading..." : `${residentMedia.length} asset(s) for ${residentQuery}`}
            </span>
          </div>
          {!residentQuery ? (
            <p className="muted" style={{ padding: "12px 0" }}>Select a resident above to see their uploaded photos and videos.</p>
          ) : (
          <div className="list" style={{ maxHeight: 500, overflow: "auto" }}>
            {residentMedia.map((m) => (
              <div className="row" key={m.id}>
                <div>
                  <div style={{ fontWeight: 700 }}>{m.name || m.blobPath}</div>
                  <div className="muted" style={{ fontSize: 12 }}>
                    {m.type} • {formatDate(m.uploadedAt)} {m.resident ? `• ${m.resident}` : ""} {m.uploadedBy ? `• ${m.uploadedBy}` : ""}
                  </div>
                </div>
                <div className="nav-actions" style={{ gap: 6 }}>
                  <button
                    className="btn ghost"
                    type="button"
                    onClick={async () => {
                      try {
                        const sas = await call<{ url: string }>({
                          url: `/api/admin/media/${m.id}/sas`,
                          method: "GET",
                        });
                        window.open(sas.url, "_blank");
                      } catch {
                        setError("Could not generate download link.");
                      }
                    }}
                  >
                    Download
                  </button>
                  <button
                    className="btn ghost"
                    type="button"
                    onClick={async () => {
                      try {
                        await call({ url: `/api/admin/media/${m.id}`, method: "DELETE" });
                        await loadData();
                      } catch {
                        setError("Could not delete media.");
                      }
                    }}
                  >
                    Delete
                  </button>
                  <button
                    className="btn ghost"
                    type="button"
                    disabled={!residentQuery.trim() || (!!m.resident && m.resident !== residentQuery.trim())}
                    onClick={async () => {
                      if (!residentQuery.trim()) {
                        setError("Select a resident first.");
                        return;
                      }
                      if (m.resident && m.resident !== residentQuery.trim()) {
                        setError("This media belongs to a different resident.");
                        return;
                      }
                      const token = `media:${m.id}`;
                      const existing = manualText.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
                      const updated = Array.from(new Set([...existing, token]));
                      setManualText(updated.join("\n"));
                      await saveResidentManual(updated);
                    }}
                  >
                    Add to playlist
                  </button>
                  <span className="tag">{m.type}</span>
                </div>
              </div>
            ))}
          </div>
          )}
        </div>
      </main>
    </>
  );
}
